name: Lixy CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  detekt-task:
    name: Simple detekt task
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
      - name: Run detekt test
        run: |
          chmod +x gradlew
          ./gradlew detekt
  jvm-tests:
    name: JVM Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Launch tests
        run: |
          chmod +x gradlew
          ./gradlew jvmTest
      - name: Run Detekt on main
        run: |
          ./gradlew detektJvmMain
  js-tests:
    name: JS (Node) Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Launch tests
        run: |
          chmod +x gradlew
          ./gradlew jsTest
      - name: Run detekt
        run: |
          ./gradlew detektJsMain
